# import * from './Operation.gql'

mutation CategoryCreate (
  $description: String!,
  $operation: Operation!
) {
  createCategory(
    description: $description,
    operation: $operation
  ) {
    id
    description
    operation
    user {
      id
      name
      email
    }
  }
}