#import './RecordFragment.gql'
# import * from './Operation.gql'

query RecordsByMonth (
  $month: String,
  $type: Operation,
  $accountsIds: [ID!],
  $categoriesIds: [ID!]
) {
  records (
    month: $month,
    type: $type,
    accountsIds: $accountsIds,
    categoriesIds: $categoriesIds
  ) {
    ...RecordFragment
  }
}